import React, { useState } from "react";
import MultiSymbol from "./MultiSymbol";
import SingleSymbol from "./SingleSymbol";
import "../App.css"; // shared glow/pulse animations

const TradeDashboard = () => {
  const [view, setView] = useState("multi");

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-center justify-center mb-6 space-y-3 md:space-y-0 md:space-x-4">
        <h1 className="text-3xl md:text-4xl font-extrabold text-gray-800 drop-shadow-lg">
          📊 HCO Quant Dashboard
        </h1>
        <span className="bg-gradient-to-r from-yellow-400 to-yellow-500 text-black font-semibold px-4 py-1 rounded-full shadow-lg animate-pulse">
          🤖 AI-powered signals
        </span>
      </div>

      {/* Description */}
      <p className="text-gray-600 mb-6 text-center md:text-lg">
        All signals, confidence levels, and AI commentary are generated by HCO Quant AI agents. 
        Choose a multi-symbol or single-symbol view for real-time AI analysis and smarter trades.
      </p>

      {/* View Toggle Buttons */}
      <div className="mb-6 flex justify-center space-x-3">
        <button
          onClick={() => setView("multi")}
          className={`px-5 py-2 rounded-lg font-semibold transition-colors duration-300 ${
            view === "multi"
              ? "bg-blue-600 text-white shadow-md hover:shadow-lg"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          Multi-Symbol
        </button>
        <button
          onClick={() => setView("single")}
          className={`px-5 py-2 rounded-lg font-semibold transition-colors duration-300 ${
            view === "single"
              ? "bg-blue-600 text-white shadow-md hover:shadow-lg"
              : "bg-gray-200 text-gray-700 hover:bg-gray-300"
          }`}
        >
          Single-Symbol
        </button>
      </div>

      {/* Render Selected Dashboard */}
      <div className="transition-all duration-500">
        {view === "multi" ? <MultiSymbol /> : <SingleSymbol />}
      </div>
    </div>
  );
};

export default TradeDashboard;

